package material

type MetalType uint64

func (t MetalType) Name() string             { return metalTypes[t].name }
func (t MetalType) Color() string            { return metalTypes[t].color0 }
func (t MetalType) OreColor() string         { return metalTypes[t].color1 }
func (t MetalType) Strength() uint64         { return metalTypes[t].strength } //TODO: Remove
func (t MetalType) Density() uint64          { return metalTypes[t].density }
func (t MetalType) Durability() uint64       { return metalTypes[t].durability }
func (t MetalType) Power() uint64            { return metalTypes[t].power }
func (t MetalType) Resistance() uint64       { return metalTypes[t].resist }
func (t MetalType) Swiftness() uint64        { return metalTypes[t].swift }
func (t MetalType) Spirituality() uint64     { return metalTypes[t].spirit }
func (t MetalType) MeleeDamage() uint64      { return metalTypes[t].meleeDmg }
func (t MetalType) MagicDamage() uint64      { return metalTypes[t].magicDmg }
func (t MetalType) AttackSpeed() uint64      { return metalTypes[t].attackSpd }
func (t MetalType) MeleeDefense() uint64     { return metalTypes[t].meleeDef }
func (t MetalType) MagicDefense() uint64     { return metalTypes[t].magicDef }
func (t MetalType) MovementSpeed() uint64    { return metalTypes[t].moveSpd }
func (t MetalType) Health() uint64           { return metalTypes[t].health }
func (t MetalType) MiningStrength() uint64   { return metalTypes[t].mining }
func (t MetalType) ChoppingStrength() uint64 { return metalTypes[t].chopping }
func (t MetalType) HealthStructure() uint64  { return metalTypes[t].healthStrc }

var metalTypes = []struct {
	name       string
	color0     string
	color1     string
	strength   uint64 //TODO: Remove
	density    uint64
	durability uint64
	power      uint64
	resist     uint64
	swift      uint64
	spirit     uint64
	//element    []string
	meleeDmg   uint64
	magicDmg   uint64
	attackSpd  uint64
	meleeDef   uint64
	magicDef   uint64
	moveSpd    uint64
	health     uint64 //health bonus to equipment
	mining     uint64
	chopping   uint64
	gatherSpd  uint64
	healthStrc uint64 //health for structure
}{
	{
		name:       "metal0",
		strength:   5 << 0,
		color0:     "#000",
		color1:     "#000",
		density:    300,
		durability: 0,
		power:      1,
		resist:     2,
		swift:      3,
		spirit:     4,
		//element:  {"dogs","kittens"}
		meleeDmg:   5,
		magicDmg:   6,
		attackSpd:  7,
		meleeDef:   8,
		magicDef:   9,
		moveSpd:    10,
		health:     11,
		mining:     12,
		chopping:   13,
		gatherSpd:  14,
		healthStrc: 15,
	},
	{
		name:       "metal1",
		strength:   5 << 0,
		color0:     "#111",
		color1:     "#111",
		density:    310,
		durability: 1,
		power:      2,
		resist:     3,
		swift:      4,
		spirit:     5,
		//element:  {"dogs","kittens"}
		meleeDmg:   6,
		magicDmg:   7,
		attackSpd:  8,
		meleeDef:   9,
		magicDef:   10,
		moveSpd:    11,
		health:     12,
		mining:     13,
		chopping:   14,
		gatherSpd:  15,
		healthStrc: 0,
	},
	{
		name:       "metal2",
		strength:   5 << 0,
		color0:     "#222",
		color1:     "#222",
		density:    320,
		durability: 2,
		power:      3,
		resist:     4,
		swift:      5,
		spirit:     6,
		//element:  {"dogs","kittens"}
		meleeDmg:   7,
		magicDmg:   8,
		attackSpd:  9,
		meleeDef:   10,
		magicDef:   11,
		moveSpd:    12,
		health:     13,
		mining:     14,
		chopping:   15,
		gatherSpd:  0,
		healthStrc: 1,
	},
	{
		name:       "metal3",
		strength:   5 << 0,
		color0:     "#333",
		color1:     "#333",
		density:    330,
		durability: 3,
		power:      4,
		resist:     5,
		swift:      6,
		spirit:     7,
		//element:  {"dogs","kittens"}
		meleeDmg:   8,
		magicDmg:   9,
		attackSpd:  10,
		meleeDef:   11,
		magicDef:   12,
		moveSpd:    13,
		health:     14,
		mining:     15,
		chopping:   0,
		gatherSpd:  1,
		healthStrc: 2,
	},
	{
		name:       "metal4",
		strength:   5 << 0,
		color0:     "#444",
		color1:     "#444",
		density:    340,
		durability: 4,
		power:      5,
		resist:     6,
		swift:      7,
		spirit:     8,
		//element:  {"dogs","kittens"}
		meleeDmg:   9,
		magicDmg:   10,
		attackSpd:  11,
		meleeDef:   12,
		magicDef:   13,
		moveSpd:    14,
		health:     15,
		mining:     0,
		chopping:   1,
		gatherSpd:  2,
		healthStrc: 3,
	},
	{
		name:       "metal5",
		strength:   5 << 0,
		color0:     "#555",
		color1:     "#555",
		density:    350,
		durability: 5,
		power:      6,
		resist:     7,
		swift:      8,
		spirit:     9,
		//element:  {"dogs","kittens"}
		meleeDmg:   10,
		magicDmg:   11,
		attackSpd:  12,
		meleeDef:   13,
		magicDef:   14,
		moveSpd:    15,
		health:     0,
		mining:     1,
		chopping:   2,
		gatherSpd:  3,
		healthStrc: 4,
	},
	{
		name:       "metal6",
		strength:   5 << 0,
		color0:     "#666",
		color1:     "#666",
		density:    360,
		durability: 6,
		power:      7,
		resist:     8,
		swift:      9,
		spirit:     10,
		//element:  {"dogs","kittens"}
		meleeDmg:   11,
		magicDmg:   12,
		attackSpd:  13,
		meleeDef:   14,
		magicDef:   15,
		moveSpd:    0,
		health:     1,
		mining:     2,
		chopping:   3,
		gatherSpd:  4,
		healthStrc: 5,
	},
	{
		name:       "metal7",
		strength:   5 << 0,
		color0:     "#777",
		color1:     "#777",
		density:    370,
		durability: 7,
		power:      8,
		resist:     9,
		swift:      10,
		spirit:     11,
		//element:  {"dogs","kittens"}
		meleeDmg:   12,
		magicDmg:   13,
		attackSpd:  14,
		meleeDef:   15,
		magicDef:   0,
		moveSpd:    1,
		health:     2,
		mining:     3,
		chopping:   4,
		gatherSpd:  5,
		healthStrc: 6,
	},
	{
		name:       "metal8",
		strength:   5 << 0,
		color0:     "#888",
		color1:     "#888",
		density:    380,
		durability: 8,
		power:      9,
		resist:     10,
		swift:      11,
		spirit:     12,
		//element:  {"dogs","kittens"}
		meleeDmg:   13,
		magicDmg:   14,
		attackSpd:  15,
		meleeDef:   0,
		magicDef:   1,
		moveSpd:    2,
		health:     3,
		mining:     4,
		chopping:   5,
		gatherSpd:  6,
		healthStrc: 7,
	},
	{
		name:       "metal9",
		strength:   5 << 0,
		color0:     "#999",
		color1:     "#999",
		density:    390,
		durability: 9,
		power:      10,
		resist:     11,
		swift:      12,
		spirit:     13,
		//element:  {"dogs","kittens"}
		meleeDmg:   14,
		magicDmg:   15,
		attackSpd:  0,
		meleeDef:   1,
		magicDef:   2,
		moveSpd:    3,
		health:     4,
		mining:     5,
		chopping:   6,
		gatherSpd:  7,
		healthStrc: 8,
	},
	{
		name:       "metal10",
		strength:   5 << 0,
		color0:     "#aaa",
		color1:     "#aaa",
		density:    400,
		durability: 10,
		power:      11,
		resist:     12,
		swift:      13,
		spirit:     14,
		//element:  {"dogs","kittens"}
		meleeDmg:   15,
		magicDmg:   0,
		attackSpd:  1,
		meleeDef:   2,
		magicDef:   3,
		moveSpd:    4,
		health:     5,
		mining:     6,
		chopping:   7,
		gatherSpd:  8,
		healthStrc: 9,
	},
	{
		name:       "metal11",
		strength:   5 << 0,
		color0:     "#bbb",
		color1:     "#bbb",
		density:    410,
		durability: 11,
		power:      12,
		resist:     13,
		swift:      14,
		spirit:     15,
		//element:  {"dogs","kittens"}
		meleeDmg:   0,
		magicDmg:   1,
		attackSpd:  2,
		meleeDef:   3,
		magicDef:   4,
		moveSpd:    5,
		health:     6,
		mining:     7,
		chopping:   8,
		gatherSpd:  9,
		healthStrc: 10,
	},
	{
		name:       "metal12",
		strength:   5 << 0,
		color0:     "#ccc",
		color1:     "#ccc",
		density:    420, //smoke weed erryday
		durability: 12,
		power:      13,
		resist:     14,
		swift:      15,
		spirit:     0,
		//element:  {"dogs","kittens"}
		meleeDmg:   1,
		magicDmg:   2,
		attackSpd:  3,
		meleeDef:   4,
		magicDef:   5,
		moveSpd:    6,
		health:     7,
		mining:     8,
		chopping:   9,
		gatherSpd:  10,
		healthStrc: 11,
	},
	{
		name:       "metal13",
		strength:   5 << 0,
		color0:     "#ddd",
		color1:     "#ddd",
		density:    430,
		durability: 13,
		power:      14,
		resist:     15,
		swift:      0,
		spirit:     1,
		//element:  {"dogs","kittens"}
		meleeDmg:   2,
		magicDmg:   3,
		attackSpd:  4,
		meleeDef:   5,
		magicDef:   6,
		moveSpd:    7,
		health:     8,
		mining:     9,
		chopping:   10,
		gatherSpd:  11,
		healthStrc: 12,
	},
	{
		name:       "metal14",
		strength:   5 << 0,
		color0:     "#eee",
		color1:     "#eee",
		density:    440,
		durability: 14,
		power:      15,
		resist:     0,
		swift:      1,
		spirit:     2,
		//element:  {"dogs","kittens"}
		meleeDmg:   3,
		magicDmg:   4,
		attackSpd:  5,
		meleeDef:   6,
		magicDef:   7,
		moveSpd:    8,
		health:     9,
		mining:     10,
		chopping:   11,
		gatherSpd:  12,
		healthStrc: 13,
	},
	{
		name:       "metal15",
		strength:   5 << 0,
		color0:     "#fff",
		color1:     "#fff",
		density:    450,
		durability: 15,
		power:      0,
		resist:     1,
		swift:      2,
		spirit:     3,
		//element:  {"dogs","kittens"}
		meleeDmg:   4,
		magicDmg:   5,
		attackSpd:  6,
		meleeDef:   7,
		magicDef:   8,
		moveSpd:    9,
		health:     10,
		mining:     11,
		chopping:   12,
		gatherSpd:  13,
		healthStrc: 14,
	},
}
